apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dkzblblce-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dkzblblce-python 
  name: dkzblblce-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dkzblblce-python 
